process:
    path:     /
    defaults: { _controller: "OmarSiteBundle:Process:index" }

process_show:
    path:     /{id}/show
    defaults: { _controller: "OmarSiteBundle:Process:show" }

process_new:
    path:     /new
    defaults: { _controller: "OmarSiteBundle:Process:new" }

process_create:
    path:     /create
    defaults: { _controller: "OmarSiteBundle:Process:create" }
    requirements: { _method: post }

process_edit:
    path:     /{id}/edit
    defaults: { _controller: "OmarSiteBundle:Process:edit" }

process_update:
    path:     /{id}/update
    defaults: { _controller: "OmarSiteBundle:Process:update" }
    requirements: { _method: post|put }

process_delete:
    path:     /{id}/delete
    defaults: { _controller: "OmarSiteBundle:Process:delete" }
    requirements: { _method: post|delete }
